# POSTTEST 4 ( DATA PREPROCESSING)

In [ ]:
Nama  : Rianawati
NIM   : 2009106132
Kelas  : C2 20

In [137]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Data Split
from sklearn.model_selection import train_test_split #testing dan training
# Data Transforming
from sklearn.preprocessing import StandardScaler #standarisasi
from sklearn.preprocessing import MinMaxScaler #normalisasi
# Data Cleaning
from sklearn.impute import SimpleImputer #subtitusi nilai
# Data Encoding
from sklearn.preprocessing import OrdinalEncoder #encoder
from sklearn.preprocessing import OneHotEncoder #onehot

Record File "countries of the world.csv"

In [211]:
df = pd.read_csv('countries of the world.csv')
df.head()

Country                               Region  Population  \
0     Afghanistan         ASIA (EX. NEAR EAST)             31056997   
1         Albania   EASTERN EUROPE                          3581655   
2         Algeria   NORTHERN AFRICA                        32930091   
3  American Samoa   OCEANIA                                   57794   
4         Andorra   WESTERN EUROPE                            71201   

   Area (sq. mi.) Pop. Density (per sq. mi.) Coastline (coast/area ratio)  \
0          647500                       48,0                         0,00   
1           28748                      124,6                         1,26   
2         2381740                       13,8                         0,04   
3             199                      290,4                        58,29   
4             468                      152,1                         0,00   

  Net migration Infant mortality (per 1000 births)  GDP ($ per capita)  \
0         23,06                             163,07               700.0   
1         -4,93                              21,52              4500.0   
2         -0,39                                 31              6000.0   
3        -20,71                               9,27              8000.0   
4           6,6                               4,05             19000.0   

  Literacy (%) Phones (per 1000) Arable (%) Crops (%) Other (%) Climate  \
0         36,0               3,2      12,13      0,22     87,65       1   
1         86,5              71,2      21,09      4,42     74,49       3   
2         70,0              78,1       3,22      0,25     96,53       1   
3         97,0             259,5         10        15        75       2   
4        100,0             497,2       2,22         0     97,78       3   

  Birthrate Deathrate Agriculture Industry Service  
0      46,6     20,34        0,38     0,24    0,38  
1     15,11      5,22       0,232    0,188   0,579  
2     17,14      4,61       0,101      0,6   0,298  
3     22,46      3,27         NaN      NaN     NaN  
4      8,71      6,25         NaN      NaN     NaN

In [212]:
df.keys()

Index(['Country', 'Region', 'Population', 'Area (sq. mi.)',
       'Pop. Density (per sq. mi.)', 'Coastline (coast/area ratio)',
       'Net migration', 'Infant mortality (per 1000 births)',
       'GDP ($ per capita)', 'Literacy (%)', 'Phones (per 1000)', 'Arable (%)',
       'Crops (%)', 'Other (%)', 'Climate', 'Birthrate', 'Deathrate',
       'Agriculture', 'Industry', 'Service'],
      dtype='object')

In [213]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 20 columns):
 #   Column                              Non-Null Count  Dtype  
---  ------                              --------------  -----  
 0   Country                             227 non-null    object 
 1   Region                              227 non-null    object 
 2   Population                          227 non-null    int64  
 3   Area (sq. mi.)                      227 non-null    int64  
 4   Pop. Density (per sq. mi.)          227 non-null    object 
 5   Coastline (coast/area ratio)        227 non-null    object 
 6   Net migration                       224 non-null    object 
 7   Infant mortality (per 1000 births)  224 non-null    object 
 8   GDP ($ per capita)                  226 non-null    float64
 9   Literacy (%)                        209 non-null    object 
 10  Phones (per 1000)                   223 non-null    object 
 11  Arable (%)                          225 non-n

In [214]:
df.isna().sum()

Country                                0
Region                                 0
Population                             0
Area (sq. mi.)                         0
Pop. Density (per sq. mi.)             0
Coastline (coast/area ratio)           0
Net migration                          3
Infant mortality (per 1000 births)     3
GDP ($ per capita)                     1
Literacy (%)                          18
Phones (per 1000)                      4
Arable (%)                             2
Crops (%)                              2
Other (%)                              2
Climate                               22
Birthrate                              3
Deathrate                              4
Agriculture                           15
Industry                              16
Service                               15
dtype: int64

In [215]:
print(f'panjang dataset {len(df)} baris')

panjang dataset 227 baris


DATA SPLIT

In [216]:
data = df[['Region']]
label = df['Climate']

data_train, data_test, label_train, label_test = train_test_split(data, label, test_size=.3)


In [217]:
print(f'panjang data training {len(data_train)}',
     f'panjang label training {len(label_train)}',
     f'panjang data testing {len(data_test)}',
     f'panjang label testing {len(label_test)}',
     sep='\n')

panjang data training 158
panjang label training 158
panjang data testing 69
panjang label testing 69


DATA TRANSFORMASI

In [218]:
dataset_normalisasi = df.copy()
dataset_standarirasi = df.copy()

NORMALISASI

In [219]:
scaler = MinMaxScaler()

normalize_dataset = scaler.fit_transform(dataset_normalisasi[['Area (sq. mi.)', 'Population']])

normalize_dataset = pd.DataFrame(normalize_dataset)
normalize_dataset.rename(columns={ 0 :'Area (sq. mi.)', 1 : 'Population'}, inplace=True)

normalize_dataset.head()

Area (sq. mi.)  Population
0        0.037920    0.023631
1        0.001683    0.002720
2        0.139485    0.025056
3        0.000012    0.000039
4        0.000027    0.000049

STANDARISASI

In [220]:
dataset_standarirasi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 20 columns):
 #   Column                              Non-Null Count  Dtype  
---  ------                              --------------  -----  
 0   Country                             227 non-null    object 
 1   Region                              227 non-null    object 
 2   Population                          227 non-null    int64  
 3   Area (sq. mi.)                      227 non-null    int64  
 4   Pop. Density (per sq. mi.)          227 non-null    object 
 5   Coastline (coast/area ratio)        227 non-null    object 
 6   Net migration                       224 non-null    object 
 7   Infant mortality (per 1000 births)  224 non-null    object 
 8   GDP ($ per capita)                  226 non-null    float64
 9   Literacy (%)                        209 non-null    object 
 10  Phones (per 1000)                   223 non-null    object 
 11  Arable (%)                          225 non-n

In [221]:
dataset_standarirasi.drop('Country', axis = 1, inplace= True)

In [222]:
dataset_standarirasi.drop('Region', axis = 1, inplace= True)

In [223]:
dataset_standarirasi.drop('Pop. Density (per sq. mi.)', axis = 1, inplace= True)

In [224]:
dataset_standarirasi.drop('Coastline (coast/area ratio)', axis = 1, inplace= True)

In [225]:
dataset_standarirasi.drop('Net migration', axis = 1, inplace= True)

In [226]:
dataset_standarirasi.drop('Infant mortality (per 1000 births)', axis = 1, inplace= True)

In [227]:
dataset_standarirasi.drop('Crops (%)', axis = 1, inplace= True)

In [228]:
dataset_standarirasi.drop('Literacy (%)', axis = 1, inplace= True)

In [229]:
dataset_standarirasi.drop('Phones (per 1000)', axis = 1, inplace= True)

In [230]:
dataset_standarirasi.drop('Arable (%)', axis = 1, inplace= True)

In [231]:
dataset_standarirasi.drop('Other (%)', axis = 1, inplace= True)

In [232]:
dataset_standarirasi.drop('Climate', axis = 1, inplace= True)

In [233]:
dataset_standarirasi.drop('Birthrate', axis = 1, inplace= True)

In [234]:
dataset_standarirasi.drop('Deathrate', axis = 1, inplace= True)

In [235]:
dataset_standarirasi.drop('Agriculture', axis = 1, inplace= True)

In [236]:
dataset_standarirasi.drop('Industry', axis = 1, inplace= True)

In [237]:
dataset_standarirasi.drop('Service', axis = 1, inplace= True)

In [210]:
dataset_standarirasi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Population          227 non-null    int64  
 1   Area (sq. mi.)      227 non-null    int64  
 2   GDP ($ per capita)  226 non-null    float64
dtypes: float64(1), int64(2)
memory usage: 5.4 KB


In [238]:
standart_std = StandardScaler()

scaled_data = standart_std.fit_transform(dataset_standarirasi)

print('Dataset sebelum scalling:',  # SEBELUM
      f'Nilai standar deviasi:\n{np.std(dataset_standarirasi)}',
      sep='\n', end='\n\n')

print('Dataset setelah scalling:',  # SESUDAH
      scaled_data[:6],
      f'Nilai standar deviasi: {np.std(scaled_data)}',
      sep='\n')

Dataset sebelum scalling:
Nilai standar deviasi:
Population            1.176314e+08
Area (sq. mi.)        1.786335e+06
GDP ($ per capita)    1.002688e+04
dtype: float64

Dataset setelah scalling:
[[ 0.01969468  0.02758332 -0.8965722 ]
 [-0.21387688 -0.31879748 -0.51759095]
 [ 0.03561811  0.99842051 -0.36799309]
 [-0.24383369 -0.33477937 -0.16852927]
 [-0.24371972 -0.33462878  0.92852172]
 [-0.14123115  0.36301881 -0.77689391]]
Nilai standar deviasi: nan


DATA CLEANING

In [178]:
dataset_ns = df.copy()

In [179]:
imputer_mean = SimpleImputer(strategy='mean')
imputer_median = SimpleImputer(strategy='median')
imputer_modus = SimpleImputer(strategy='most_frequent')

MODUS

In [239]:
df.isna().sum()

Country                                0
Region                                 0
Population                             0
Area (sq. mi.)                         0
Pop. Density (per sq. mi.)             0
Coastline (coast/area ratio)           0
Net migration                          3
Infant mortality (per 1000 births)     3
GDP ($ per capita)                     1
Literacy (%)                          18
Phones (per 1000)                      4
Arable (%)                             2
Crops (%)                              2
Other (%)                              2
Climate                               22
Birthrate                              3
Deathrate                              4
Agriculture                           15
Industry                              16
Service                               15
dtype: int64

In [240]:
dfmodus = df.copy()

In [241]:
dfmodus['Literacy (%)'] = imputer_modus.fit_transform(dfmodus[['Literacy (%)']])
dfmodus['Climate'] = imputer_modus.fit_transform(dfmodus[['Climate']])
dfmodus['Agriculture'] = imputer_modus.fit_transform(dfmodus[['Agriculture']])
dfmodus['Industry'] = imputer_modus.fit_transform(dfmodus[['Industry']])
dfmodus['Service'] = imputer_modus.fit_transform(dfmodus[['Service']])
dfmodus['Deathrate'] = imputer_modus.fit_transform(dfmodus[['Deathrate']])

dfmodus.isna().sum()

Country                               0
Region                                0
Population                            0
Area (sq. mi.)                        0
Pop. Density (per sq. mi.)            0
Coastline (coast/area ratio)          0
Net migration                         3
Infant mortality (per 1000 births)    3
GDP ($ per capita)                    1
Literacy (%)                          0
Phones (per 1000)                     4
Arable (%)                            2
Crops (%)                             2
Other (%)                             2
Climate                               0
Birthrate                             3
Deathrate                             0
Agriculture                           0
Industry                              0
Service                               0
dtype: int64

MEAN

In [242]:
dfmodus['GDP ($ per capita)'] = imputer_mean.fit_transform(dfmodus[['GDP ($ per capita)']])
dfmodus['Area (sq. mi.)'] = imputer_mean.fit_transform(dfmodus[['Area (sq. mi.)']])

dfmodus.isna().sum()

Country                               0
Region                                0
Population                            0
Area (sq. mi.)                        0
Pop. Density (per sq. mi.)            0
Coastline (coast/area ratio)          0
Net migration                         3
Infant mortality (per 1000 births)    3
GDP ($ per capita)                    0
Literacy (%)                          0
Phones (per 1000)                     4
Arable (%)                            2
Crops (%)                             2
Other (%)                             2
Climate                               0
Birthrate                             3
Deathrate                             0
Agriculture                           0
Industry                              0
Service                               0
dtype: int64

DATA DUPLIKAT

In [243]:
df2 = pd.read_csv('Copy.csv')
df2.head()
dataset_duplicate = df2.copy()

dataset_duplicate.duplicated().sum()

4

In [244]:
dataset_duplicate.drop_duplicates(inplace=True)

dataset_duplicate.duplicated().sum()

0

ENCODING

In [245]:
dataset_ordinal = df.copy()
dataset_one_hot = df.copy()

In [246]:
df['Region'].unique()

array(['ASIA (EX. NEAR EAST)         ',
       'EASTERN EUROPE                     ',
       'NORTHERN AFRICA                    ',
       'OCEANIA                            ',
       'WESTERN EUROPE                     ',
       'SUB-SAHARAN AFRICA                 ', 'LATIN AMER. & CARIB    ',
       'C.W. OF IND. STATES ', 'NEAR EAST                          ',
       'NORTHERN AMERICA                   ',
       'BALTICS                            '], dtype=object)

ORDINAL

In [248]:
encoder_ordinal =OrdinalEncoder()

#encoding kan
dataset_ordinal['Region'] = encoder_ordinal.fit_transform(dataset_ordinal[['Region']]).astype('int64')

#lihat
dataset_ordinal.head()

Country  Region  Population  Area (sq. mi.)  \
0     Afghanistan        0    31056997          647500   
1         Albania        3     3581655           28748   
2         Algeria        6    32930091         2381740   
3  American Samoa        8       57794             199   
4         Andorra       10       71201             468   

  Pop. Density (per sq. mi.) Coastline (coast/area ratio) Net migration  \
0                       48,0                         0,00         23,06   
1                      124,6                         1,26         -4,93   
2                       13,8                         0,04         -0,39   
3                      290,4                        58,29        -20,71   
4                      152,1                         0,00           6,6   

  Infant mortality (per 1000 births)  GDP ($ per capita) Literacy (%)  \
0                             163,07               700.0         36,0   
1                              21,52              4500.0         86,5   
2                                 31              6000.0         70,0   
3                               9,27              8000.0         97,0   
4                               4,05             19000.0        100,0   

  Phones (per 1000) Arable (%) Crops (%) Other (%) Climate Birthrate  \
0               3,2      12,13      0,22     87,65       1      46,6   
1              71,2      21,09      4,42     74,49       3     15,11   
2              78,1       3,22      0,25     96,53       1     17,14   
3             259,5         10        15        75       2     22,46   
4             497,2       2,22         0     97,78       3      8,71   

  Deathrate Agriculture Industry Service  
0     20,34        0,38     0,24    0,38  
1      5,22       0,232    0,188   0,579  
2      4,61       0,101      0,6   0,298  
3      3,27         NaN      NaN     NaN  
4      6,25         NaN      NaN     NaN

In [249]:
dataset_ordinal['Region'].unique()

array([ 0,  3,  6,  8, 10,  9,  4,  2,  5,  7,  1], dtype=int64)

ONE-HOT

In [250]:
temp_dataset = pd.get_dummies(dataset_one_hot[['Region']])

temp_dataset = pd.DataFrame(temp_dataset)

dataset_one_hot.drop('Region', axis=1, inplace=True)

dataset_one_hot = dataset_one_hot.join(temp_dataset)
dataset_one_hot.head(5)

Country  Population  Area (sq. mi.) Pop. Density (per sq. mi.)  \
0     Afghanistan     31056997          647500                       48,0   
1         Albania      3581655           28748                      124,6   
2         Algeria     32930091         2381740                       13,8   
3  American Samoa        57794             199                      290,4   
4         Andorra        71201             468                      152,1   

  Coastline (coast/area ratio) Net migration  \
0                         0,00         23,06   
1                         1,26         -4,93   
2                         0,04         -0,39   
3                        58,29        -20,71   
4                         0,00           6,6   

  Infant mortality (per 1000 births)  GDP ($ per capita) Literacy (%)  \
0                             163,07               700.0         36,0   
1                              21,52              4500.0         86,5   
2                                 31              6000.0         70,0   
3                               9,27              8000.0         97,0   
4                               4,05             19000.0        100,0   

  Phones (per 1000)  ... Region_BALTICS                              \
0               3,2  ...                                          0   
1              71,2  ...                                          0   
2              78,1  ...                                          0   
3             259,5  ...                                          0   
4             497,2  ...                                          0   

  Region_C.W. OF IND. STATES  Region_EASTERN EUROPE                       \
0                           0                                          0   
1                           0                                          1   
2                           0                                          0   
3                           0                                          0   
4                           0                                          0   

  Region_LATIN AMER. & CARIB     Region_NEAR EAST                            \
0                              0                                          0   
1                              0                                          0   
2                              0                                          0   
3                              0                                          0   
4                              0                                          0   

  Region_NORTHERN AFRICA                      \
0                                          0   
1                                          0   
2                                          1   
3                                          0   
4                                          0   

  Region_NORTHERN AMERICA                     \
0                                          0   
1                                          0   
2                                          0   
3                                          0   
4                                          0   

  Region_OCEANIA                              \
0                                          0   
1                                          0   
2                                          0   
3                                          1   
4                                          0   

  Region_SUB-SAHARAN AFRICA                   \
0                                          0   
1                                          0   
2                                          0   
3                                          0   
4                                          0   

   Region_WESTERN EUROPE                       
0                                           0  
1                                           0  
2                                           0  
3                                           0  
4                                           1  

[5 rows x 30 col