        NAMA     : Rianawati

        NIM      : 2009106132

        KELAS    : C2 2020
        
        POSTTEST : 7

In [3]:
import tensorflow as tf
import numpy as np

Membuat sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [5]:
random_tensor = tf.random.normal([5,5], mean=2., stddev=5., seed=1)
random_tensor.numpy()

array([[ 0.38067555,  6.9566846 ,  2.7012134 ,  8.286985  ,  2.4996166 ],
       [ 2.949161  ,  0.56444025, -6.7067976 , 11.359377  , -8.052252  ],
       [-5.3365145 , -4.3609943 , -1.901869  ,  6.7036514 ,  1.6917589 ],
       [-8.421263  ,  5.0711565 , -5.25546   , -2.4346762 , -2.8370433 ],
       [ 6.741592  , -1.4872496 ,  4.6957183 , -0.6485033 , -8.052682  ]],
      dtype=float32)

In [7]:
list_utt = [[1,3,5,7,9],[11,13,15,17,19],[21,23,25,27,29],[31,33,35,37,39],[41,43,45,47,49]]

utt = tf.convert_to_tensor(list_utt)
utt.numpy()

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [8]:
slicing = tf.random.normal([5,5,5])
slicing.numpy()

array([[[-1.1967124 ,  1.7779316 , -0.96410954,  0.22111323,
          1.7190084 ],
        [-0.20572706, -2.3994057 , -1.0976545 ,  0.77792674,
         -1.7546837 ],
        [ 0.3925101 ,  0.753727  , -0.22419482,  1.314287  ,
         -0.1095557 ],
        [-0.2591979 , -1.74597   ,  0.17157772, -1.6621153 ,
         -0.12673627],
        [ 0.48999238, -0.9985645 ,  0.0522005 , -0.09672368,
          0.18744488]],

       [[ 1.0566874 , -0.27149794,  1.6948912 ,  0.3358854 ,
         -0.23771721],
        [ 0.6416269 ,  0.70454955,  0.23954625, -0.03466679,
          0.27049986],
        [-0.03485564, -0.75662196, -1.1617069 , -1.3749162 ,
          0.4023056 ],
        [-1.3571919 ,  1.4796585 , -1.2887549 , -0.55407476,
          1.610371  ],
        [ 1.5021403 ,  1.1562364 ,  0.20301414,  0.86701465,
         -1.7712919 ]],

       [[-0.88632494, -1.4218055 ,  2.0979912 ,  1.2904603 ,
          0.6163971 ],
        [ 0.05511823, -0.19209193, -0.1272935 , -0.22710748,
         -0

In [16]:
slicing[3,3,3]

<tf.Tensor: shape=(), dtype=float32, numpy=0.1552416>

In [17]:
slicing[3]

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.6312864 , -1.3985616 , -0.2850355 , -0.9285845 , -0.9318297 ],
       [-1.0202675 , -0.73832935, -1.1400516 , -0.91723055, -0.8943347 ],
       [ 0.74076474,  0.8275649 ,  2.0252597 , -0.56023145, -0.8277063 ],
       [ 1.9731284 ,  0.08290863, -1.8079661 ,  0.1552416 , -0.3584762 ],
       [ 1.0385709 ,  0.8378186 ,  0.50289184,  0.1298136 , -1.4118444 ]],
      dtype=float32)>

In [18]:
tf.gather(slicing, indices=[3,3,3]).numpy()

array([[[-0.6312864 , -1.3985616 , -0.2850355 , -0.9285845 ,
         -0.9318297 ],
        [-1.0202675 , -0.73832935, -1.1400516 , -0.91723055,
         -0.8943347 ],
        [ 0.74076474,  0.8275649 ,  2.0252597 , -0.56023145,
         -0.8277063 ],
        [ 1.9731284 ,  0.08290863, -1.8079661 ,  0.1552416 ,
         -0.3584762 ],
        [ 1.0385709 ,  0.8378186 ,  0.50289184,  0.1298136 ,
         -1.4118444 ]],

       [[-0.6312864 , -1.3985616 , -0.2850355 , -0.9285845 ,
         -0.9318297 ],
        [-1.0202675 , -0.73832935, -1.1400516 , -0.91723055,
         -0.8943347 ],
        [ 0.74076474,  0.8275649 ,  2.0252597 , -0.56023145,
         -0.8277063 ],
        [ 1.9731284 ,  0.08290863, -1.8079661 ,  0.1552416 ,
         -0.3584762 ],
        [ 1.0385709 ,  0.8378186 ,  0.50289184,  0.1298136 ,
         -1.4118444 ]],

       [[-0.6312864 , -1.3985616 , -0.2850355 , -0.9285845 ,
         -0.9318297 ],
        [-1.0202675 , -0.73832935, -1.1400516 , -0.91723055,
         -0

In [19]:
tf.gather_nd(slicing, indices=[[0,2,2],[1,2,2],[2,2,2],[3,2,2],[4,2,2]]).numpy()

array([-0.22419482, -1.1617069 ,  0.06356224,  2.0252597 ,  1.2073739 ],
      dtype=float32)

Membuat sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [21]:
list_prime = [[2, 3, 5, 7, 11],[13, 17, 19, 23, 29],[31, 37, 41, 43, 47],[53, 59, 61, 71, 73],[79, 83, 89, 97, 1]]

prime_tensor = tf.constant(list_prime, dtype=tf.float32)
prime_tensor.numpy()

array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 71., 73.],
       [79., 83., 89., 97.,  1.]], dtype=float32)

Menampilkan dimensi dari kedua variable tersebut

In [22]:
random_tensor.shape

TensorShape([5, 5])

In [23]:
prime_tensor.shape

TensorShape([5, 5])

Menampilkan hasil dari perhitungan aritmatika 2 variable tersebut (Gunakan minimal 5 operator)

In [24]:
print("1. Penjumlahan :",tf.add(prime_tensor,random_tensor))
print("\n2. Pengurangan :",tf.subtract(prime_tensor,random_tensor))
print("\n3. Perkalian :",tf.multiply(prime_tensor,random_tensor))
print("\n4. Pembagian :",tf.divide(prime_tensor,random_tensor))
print("\n5. Pangkat :",tf.pow(prime_tensor,random_tensor))
print("\n9. Setara :",tf.equal(prime_tensor,random_tensor))
print("\n10. Tidak Setara :",tf.not_equal(prime_tensor,random_tensor))
print("\n14. Maximum :",tf.math.maximum(prime_tensor,random_tensor))
print("\n15. Minimum :",tf.math.minimum(prime_tensor,random_tensor))
print("\n16. Kuadrat Perbedaan :",tf.math.squared_difference(prime_tensor,random_tensor))

1. Penjumlahan : tf.Tensor(
[[ 2.3806756  9.956684   7.7012134 15.286985  13.499617 ]
 [15.949162  17.56444   12.293202  34.359375  20.947748 ]
 [25.663486  32.639008  39.09813   49.70365   48.691757 ]
 [44.578735  64.07116   55.74454   68.56532   70.16296  ]
 [85.74159   81.51275   93.69572   96.351494  -7.052682 ]], shape=(5, 5), dtype=float32)

2. Pengurangan : tf.Tensor(
[[ 1.6193244 -3.9566846  2.2987866 -1.2869854  8.500383 ]
 [10.050838  16.43556   25.706799  11.640623  37.052254 ]
 [36.336514  41.360992  42.90187   36.29635   45.308243 ]
 [61.421265  53.928844  66.25546   73.43468   75.83704  ]
 [72.25841   84.48725   84.30428   97.648506   9.052682 ]], shape=(5, 5), dtype=float32)

3. Perkalian : tf.Tensor(
[[   0.7613511   20.870054    13.506067    58.008896    27.495783 ]
 [  38.339092     9.595484  -127.42915    261.26566   -233.5153   ]
 [-165.43195   -161.3568     -77.97663    288.25702     79.512665 ]
 [-446.32693    299.19824   -320.58304   -172.86201   -207.10416  ]
 [

Menampilkan nilai maksimal dan minimal dari variable random_tensor

In [25]:
tf.argmax(random_tensor, axis=0).numpy()#max baris random_tensor

array([4, 0, 4, 1, 0], dtype=int64)

In [26]:
tf.argmax(random_tensor, axis=1).numpy()#max kolom random_tensor

array([3, 3, 3, 1, 0], dtype=int64)

In [27]:
tf.argmin(random_tensor, axis=0).numpy()#min baris random_tensor

array([3, 2, 1, 3, 4], dtype=int64)

In [28]:
tf.argmin(random_tensor, axis=1).numpy()#min kolom random_tensor

array([0, 4, 0, 0, 4], dtype=int64)

Menampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [29]:
tf.concat([random_tensor,prime_tensor], axis=0).numpy()#penggabungan baris

array([[ 0.38067555,  6.9566846 ,  2.7012134 ,  8.286985  ,  2.4996166 ],
       [ 2.949161  ,  0.56444025, -6.7067976 , 11.359377  , -8.052252  ],
       [-5.3365145 , -4.3609943 , -1.901869  ,  6.7036514 ,  1.6917589 ],
       [-8.421263  ,  5.0711565 , -5.25546   , -2.4346762 , -2.8370433 ],
       [ 6.741592  , -1.4872496 ,  4.6957183 , -0.6485033 , -8.052682  ],
       [ 2.        ,  3.        ,  5.        ,  7.        , 11.        ],
       [13.        , 17.        , 19.        , 23.        , 29.        ],
       [31.        , 37.        , 41.        , 43.        , 47.        ],
       [53.        , 59.        , 61.        , 71.        , 73.        ],
       [79.        , 83.        , 89.        , 97.        ,  1.        ]],
      dtype=float32)

In [30]:
tf.concat([random_tensor,prime_tensor], axis=1).numpy()#penggabungan kolom

array([[ 0.38067555,  6.9566846 ,  2.7012134 ,  8.286985  ,  2.4996166 ,
         2.        ,  3.        ,  5.        ,  7.        , 11.        ],
       [ 2.949161  ,  0.56444025, -6.7067976 , 11.359377  , -8.052252  ,
        13.        , 17.        , 19.        , 23.        , 29.        ],
       [-5.3365145 , -4.3609943 , -1.901869  ,  6.7036514 ,  1.6917589 ,
        31.        , 37.        , 41.        , 43.        , 47.        ],
       [-8.421263  ,  5.0711565 , -5.25546   , -2.4346762 , -2.8370433 ,
        53.        , 59.        , 61.        , 71.        , 73.        ],
       [ 6.741592  , -1.4872496 ,  4.6957183 , -0.6485033 , -8.052682  ,
        79.        , 83.        , 89.        , 97.        ,  1.        ]],
      dtype=float32)

Menampilkan hasil sorting dari kedua variable di atas. (descending)

In [31]:
sort_random_tensor1 = tf.sort(random_tensor, direction="DESCENDING")
sort_random_tensor1.numpy()

array([[ 8.286985  ,  6.9566846 ,  2.7012134 ,  2.4996166 ,  0.38067555],
       [11.359377  ,  2.949161  ,  0.56444025, -6.7067976 , -8.052252  ],
       [ 6.7036514 ,  1.6917589 , -1.901869  , -4.3609943 , -5.3365145 ],
       [ 5.0711565 , -2.4346762 , -2.8370433 , -5.25546   , -8.421263  ],
       [ 6.741592  ,  4.6957183 , -0.6485033 , -1.4872496 , -8.052682  ]],
      dtype=float32)

In [32]:
sort_random_tensor2 = tf.argsort(random_tensor, direction="DESCENDING")
sort_random_tensor2.numpy()

array([[3, 1, 2, 4, 0],
       [3, 0, 1, 2, 4],
       [3, 4, 2, 1, 0],
       [1, 3, 4, 2, 0],
       [0, 2, 3, 1, 4]])

In [33]:
sort_prime_tensor1 = tf.sort(prime_tensor, direction="DESCENDING")
sort_prime_tensor1.numpy()

array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [73., 71., 61., 59., 53.],
       [97., 89., 83., 79.,  1.]], dtype=float32)

In [34]:
sort_prime_tensor2 = tf.argsort(prime_tensor, direction="DESCENDING")
sort_prime_tensor2.numpy()

array([[4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [3, 2, 1, 0, 4]])